### ISSUE TITLE
GCP Secret Manager Config Client timeouts

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-gcp#1011]
### Expected Behavior

Reads configuration from GCP secret manager.

### Actual Behaviour

We keep micronaut configuration for a service in GCP secret manager.

Since upgrade to micronaut-platform 4.2.+ starting server fails with exception bellow.

Downgrading to 4.1.6 fixes error. Seams like a problem is tied to micronaut-core somehow and not directly to micronaut-gcp.

```
j.u.c.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
	at r.c.p.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:296)
	at r.c.p.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:281)
	at r.c.p.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:420)
	at r.c.p.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162)
	at r.c.p.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:270)
	at r.c.p.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:285)
	at r.c.s.SchedulerTask.call(SchedulerTask.java:68)
	at r.c.s.SchedulerTask.call(SchedulerTask.java:28)
	at j.u.c.FutureTask.run(FutureTask.java:317)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1623)
Wrapped by: r.c.Exceptions$ReactiveException: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
	at r.core.Exceptions.propagate(Exceptions.java:408)
	at r.c.p.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
	at r.c.publisher.Mono.block(Mono.java:1728)
	at i.m.d.c.c.DistributedPropertySourceLocator.findPropertySources(DistributedPropertySourceLocator.java:79)
	... 9 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at r.c.p.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		... 11 common frames omitted
Wrapped by: i.m.c.e.ConfigurationException: Read timeout occurred reading distributed configuration from client: compositeConfigurationClient(GCP Secret Manager Config Client)
	at i.m.d.c.c.DistributedPropertySourceLocator.findPropertySources(DistributedPropertySourceLocator.java:86)
	at i.m.c.DefaultApplicationContext$RuntimeConfiguredEnvironment.readPropertySourceList(DefaultApplicationContext.java:905)
	at i.m.c.e.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:439)
	at i.m.c.e.DefaultEnvironment.start(DefaultEnvironment.java:277)
	at i.m.c.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:891)
	at i.m.c.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:860)
	at i.m.c.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:263)
	at i.m.c.DefaultApplicationContext.start(DefaultApplicationContext.java:198)
	at i.m.r.Micronaut.start(Micronaut.java:73)
```

### Environment Information

GCP K8S with java 21

### Version

4.2

**Comment by vnesek** [comment]
Tried out platform 4.2.3, still the same.

**Comment by vnesek** [comment]
Tried out platform 4.3.0, looks like it's fixed
