### ISSUE TITLE
Testing apps locally with the gcp emulator for background function

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-gcp#1032]
### Expected Behavior

The Intellj IDE should pick up the emulator location

### Actual Behaviour

```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Project 'project:adept-button-401609' not found or deleted.
reactor.core.Exceptions$ReactiveException: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Project 'project:adept-button-401609' not found or deleted.
    at reactor.core.Exceptions.propagate(Exceptions.java:408)
    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
    at reactor.core.publisher.Mono.block(Mono.java:1712)
    at io.micronaut.gcp.pubsub.intercept.PubSubClientIntroductionAdvice.intercept(PubSubClientIntroductionAdvice.java:185)
    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
    at fete.bird.IFileUploadClient$Intercepted.pubSubMessage(Unknown Source)
    at fete.bird.FileUploadController.getFileName(FileUploadController.java:26)
    at fete.bird.$FileUploadController$Definition$Exec.dispatch(Unknown Source)
    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
    at io.micronaut.context.DefaultBeanContext$BeanContextExecutionHandle.invoke(DefaultBeanContext.java:4282)
    at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:223)
    at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
    at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:480)
    at io.micronaut.http.server.RouteExecutor.callRoute(RouteExecutor.java:470)
    at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$2(RequestLifecycle.java:146)
    at io.micronaut.core.execution.ImperativeExecutionFlowImpl.flatMap(ImperativeExecutionFlowImpl.java:72)
    at io.micronaut.http.server.RequestLifecycle.lambda$normalFlow$4(RequestLifecycle.java:146)
```

### Steps To Reproduce

I have two micronaut GCP applications

HTTP function
Background function
HTTP function is a regular micronuat application with the below dependency, and using pub/sub I am trying to trigger the background function

`implementation("io.micronaut.gcp:micronaut-gcp-pubsub")`

**Controller**

```
@Introspected
public class PubSubMessage {
    String data;
    Map<String, String> attributes;
    String messageId;
    String publishTime;
}

    @Controller("/")
    public record FileUploadController(IFileUploadClient iFileUploadClient){
    
        public String getFileName() {
            iFileUploadClient.pubSubMessage(new PubSubMessage());
            return "THis is file 1";
        }
    }

    @PubSubClient
    public interface IFileUploadClient {
        @Topic("projects/test-project/topics/micronaut-devices")
        void pubSubMessage(PubSubMessage pubSubMessage);
    }
```

**Background-function**

```
public class Function extends GoogleFunctionInitializer
        implements BackgroundFunction<PubSubMessage> {


    @Override
    public void accept(PubSubMessage message, Context context) {
        System.out.println("Hello world");
    }
}

class PubSubMessage {
    String data;
    Map<String, String> attributes;
    String messageId;
    String publishTime;
}
```

I am running the HTTP function as regular micronaut application with runtime("netty"), however for the background function, I have setup the gradle task

```
tasks.register("runFunction", JavaExec) {
  main = 'com.google.cloud.functions.invoker.runner.Invoker'
  classpath(configurations.invoker)
  inputs.files(configurations.runtimeClasspath, sourceSets.main.output)
  args(
    '--target', project.findProperty('run.functionTarget') ?: 'fete.bird.Function',
    '--port', project.findProperty('run.port') ?: 8081
  )
  doFirst {
    args('--classpath', files(configurations.runtimeClasspath, sourceSets.main.output).asPath)
  }
}
```

Using an emulator with the below command

`Gcloud beta emulators pub sub start --host-port=127.0.0.1:8086 --project=test-project`

![image](https://github.com/micronaut-projects/micronaut-gcp/assets/84489031/c9b20acf-a16c-4d32-8642-5a13c01ac9a4)

Exception is thrown when publish the message

 iFileUploadClient.pubSubMessage(new PubSubMessage());
In the micronaut documentation it is mentioned that The framework supports automatic switching of the TransportChannelProvider to use PUBSUB_EMULATOR_HOST if this variable is set on the environment.

Make sure that you also set GCP_PROJECT_ID to be the same as the project you have configured the emulator to use. Otherwise the framework may pick up the projectId used by the default credentials.

The framework is somehow picking the different projects that I have set using the command --project=test-project

The error is INVALID_ARGUMENT: Project 'project:adept-button-401609' not found or deleted.

I have exposed the below command as well

`$(gcloud beta emulators pubsub env-init)`

```
export PUBSUB_EMULATOR_HOST=127.0.0.1:8086
export PUBSUB_PROJECT_ID=test-project
```

I have also exported the project id as export GCP_PROJECT_ID="test-project" still the same issue

When application is running the default credential is used

![image](https://github.com/micronaut-projects/micronaut-gcp/assets/84489031/4617a972-b704-4cc1-9b9b-d2a14b75432d)

**.properties file**

`gcp.project-id=test-project`
GitHub - https://github.com/anandjaisy/gcp-background-function

In the Application Default Credentials works on mac

**.properties file**

`gcp.project-id=test-project`

GitHub - https://github.com/anandjaisy/gcp-background-function

In the Application Default Credentials works on mac

It is using this json

```
{
  "client_id": "xxx",
  "client_secret": "xxx",
  "quota_project_id": "adept-button-401609",
  "refresh_token": "xxx",
  "type": "authorized_user"
}
```
However, it should use the emulator version. Due to some reason, the micronaut application is not picking up

### Environment Information

- MAC OS 
- openjdk version "21.0.2" 2024-01-16 LTS
- OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
- OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode)

### Example Application

https://github.com/anandjaisy/gcp-background-function

### Version

4.2.4

**Comment by anandjaisy** [comment]
The issue was the export env variable needs to be in same session as the application is running.

Terminal

export PUBSUB_EMULATOR_HOST=localhost:8085

export PUBSUB_PROJECT_ID=white-stacker-412404
Then

./gradlew run
By setting all the env variables in the same terminal session, the application works.

Intellj IDE

Edit configuration and set the below env variable

PUBSUB_PROJECT_ID=white-stacker-412404;PUBSUB_EMULATOR_HOST=localhost:8085
