### ISSUE TITLE
Cannot build GraalVM native image with micronaut-gcp-logging

### ISSUE THREAD

**Issue by Hixon10** [micronaut-projects/micronaut-gcp#287]
Hello,

I want to enable `json` logs in my application. So, I used this guide https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#logging

```
implementation("io.micronaut.gcp:micronaut-gcp-logging:3.2.1")
```

```
<configuration>
    <include resource="io/micronaut/gcp/logging/logback-json-appender.xml" /> 
    <root level="INFO">
        <appender-ref ref="CONSOLE_JSON" /> 
    </root>
</configuration>
```

As result, my native docker image has failed with error - https://github.com/Hixon10/telegram-calendar-notifications/runs/1322773581?check_suite_focus=true

```
[application:24]     analysis:  71,692.31 ms,  2.86 GB
Error: Classes that should be initialized at run time got initialized during image building:
 com.google.api.client.util.DateTime was unintentionally initialized at build time. To see why com.google.api.client.util.DateTime got initialized use -H:+TraceClassInitialization
io.opencensus.trace.SpanContext was unintentionally initialized at build time. To see why io.opencensus.trace.SpanContext got initialized use -H:+TraceClassInitialization
com.google.api.client.http.HttpRequest was unintentionally initialized at build time. To see why com.google.api.client.http.HttpRequest got initialized use -H:+TraceClassInitialization
com.google.common.base.Throwables was unintentionally initialized at build time. To see why com.google.common.base.Throwables got initialized use -H:+TraceClassInitialization
....

**Comment by viniciusccarvalho** [comment]
@graemerocher @Hixon10 Most google libraries are not compatible with graalvm at the moment. There's a lot of work being done by the java client team to fix this, and there's a fork of the client libraries (pubsub being the most mature) that includes `native-image.properties`. 

I'll find their issue and link here

**Comment by viniciusccarvalho** [comment]
This has been fixed on the latest : https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support You need to include the google new graal support libraries along with the micronaut libraries. I've tested both pubsub and logging modules and they compile to native images without issues. We just need to update docs to reflect that.

**Comment by tchiotludo** [comment]
Hi @viniciusccarvalho, 

I'm trying to build using `google-cloud-graalvm-support`, I've this error during the build : 

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.threeten.bp.Duration was unintentionally initialized at build time. io.micronaut.gcp.pubsub.configuration.PublisherConfigurationProperties caused initialization of this class with the following trace: 
        at org.threeten.bp.Duration.<clinit>(Duration.java:99)
        at io.micronaut.gcp.pubsub.configuration.PublisherConfigurationProperties.<clinit>(PublisherConfigurationProperties.java:41)
```
I have the feeling that it's only a import trouble no ?

**Comment by viniciusccarvalho** [comment]
This was fixed via this pr: https://github.com/micronaut-projects/micronaut-gcp/pull/375, it may not be on the latest build. You can easily fix it in the meantime by adding the content of that file on your `META-INF/native-image/io.micronaut/gcp-pubsub/native-image.properties `

**Comment by tchiotludo** [comment]
thnkas @viniciusccarvalho, adding the files works well, thanks ;)

**Comment by tchiotludo** [comment]
Still me :smile: 
In fact, it works well with pubsub but not with `io.micronaut.gcp:micronaut-gcp-logging` 
I've try to report the issue here : https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/issues/96, not really sure that `google-cloud-graalvm-support` will handle this or not.

**Comment by tchiotludo** [comment]
Here is a sample project: https://github.com/tchiotludo/micronaut-gcp-logs with the error : 
```
Error: Classes that should be initialized at run time got initialized during image building:
 io.opencensus.trace.EndSpanOptions was unintentionally initialized at build time. To see why io.opencensus.trace.EndSpanOptions got initialized use --trace-class-initialization=io.opencensus.trace.EndSpanOptions
io.opencensus.trace.AutoValue_EndSpanOptions was unintentionally initialized at build time. To see why io.opencensus.trace.AutoValue_EndSpanOptions got initialized use --trace-class-initialization=io.opencensus.trace.AutoValue_EndSpanOptions
com.google.cloud.ServiceOptions was unintentionally initialized at build time. To see why com.google.cloud.ServiceOptions got initialized use --trace-class-initialization=com.google.cloud.ServiceOptions
com.google.common.base.Throwables was unintentionally initialized at build time. To see why com.google.common.base.Throwables got initialized use --trace-class-initialization=com.google.common.base.Throwables
io.opencensus.trace.Status was unintentionally initialized at build time. To see why io.opencensus.trace.Status got initialized use --trace-class-initialization=io.opencensus.trace.Status
com.google.api.client.http.HttpTransport was unintentionally initialized at build time. To see why com.google.api.client.http.HttpTransport got initialized use --trace-class-initialization=com.google.api.client.http.HttpTransport
com.google.api.client.http.OpenCensusUtils was unintentionally initialized at build time. To see why com.google.api.client.http.OpenCensusUtils got initialized use --trace-class-initialization=com.google.api.client.http.OpenCensusUtils
com.google.api.client.http.javanet.NetHttpTransport was unintentionally initialized at build time. To see why com.google.api.client.http.javanet.NetHttpTransport got initialized use --trace-class-initialization=com.google.api.client.http.javanet.NetHttpTransport
com.google.api.client.util.StringUtils was unintentionally initialized at build time. To see why com.google.api.client.util.StringUtils got initialized use --trace-class-initialization=com.google.api.client.util.StringUtils
com.google.api.client.http.HttpMediaType was unintentionally initialized at build time. To see why com.google.api.client.http.HttpMediaType got initialized use --trace-class-initialization=com.google.api.client.http.HttpMediaType
com.google.api.client.util.escape.CharEscapers was unintentionally initialized at build time. To see why com.google.api.client.util.escape.CharEscapers got initialized use --trace-class-initialization=com.google.api.client.util.escape.CharEscapers
com.google.common.collect.ImmutableList was unintentionally initialized at build time. To see why com.google.common.collect.ImmutableList got initialized use --trace-class-initialization=com.google.common.collect.ImmutableList
io.opencensus.trace.BlankSpan was unintentionally initialized at build time. To see why io.opencensus.trace.BlankSpan got initialized use --trace-class-initialization=io.opencensus.trace.BlankSpan
com.google.cloud.PlatformInformation was unintentionally initialized at build time. To see why com.google.cloud.PlatformInformation got initialized use --trace-class-initialization=com.google.cloud.PlatformInformation
com.google.api.client.http.GenericUrl was unintentionally initialized at build time. To see why com.google.api.client.http.GenericUrl got initialized use --trace-class-initialization=com.google.api.client.http.GenericUrl
com.google.api.client.util.DateTime was unintentionally initialized at build time. To see why com.google.api.client.util.DateTime got initialized use --trace-class-initialization=com.google.api.client.util.DateTime
com.google.api.client.http.HttpRequest was unintentionally initialized at build time. To see why com.google.api.client.http.HttpRequest got initialized use --trace-class-initialization=com.google.api.client.http.HttpRequest
com.google.common.io.Closer was unintentionally initialized at build time. To see why com.google.common.io.Closer got initialized use --trace-class-initialization=com.google.common.io.Closer
io.opencensus.trace.Span was unintentionally initialized at build time. To see why io.opencensus.trace.Span got initialized use --trace-class-initialization=io.opencensus.trace.Span
com.google.common.collect.RegularImmutableList was unintentionally initialized at build time. To see why com.google.common.collect.RegularImmutableList got initialized use --trace-class-initialization=com.google.common.collect.RegularImmutableList
com.google.api.client.util.Data was unintentionally initialized at build time. To see why com.google.api.client.util.Data got initialized use --trace-class-initialization=com.google.api.client.util.Data

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

**Comment by viniciusccarvalho** [comment]
I have not cloned that repo, but the build is missing the https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support dependency did you try to build with that dependency on the classpath?

**Comment by tchiotludo** [comment]
oups! forgot a commit ! 
I've just added it with this error : 
```
Error: Classes that should be initialized at run time got initialized during image building:
 com.google.api.client.http.GenericUrl was unintentionally initialized at build time. To see why com.google.api.client.http.GenericUrl got initialized use --trace-class-initialization=com.google.api.client.http.GenericUrl
io.opencensus.trace.BlankSpan was unintentionally initialized at build time. To see why io.opencensus.trace.BlankSpan got initialized use --trace-class-initialization=io.opencensus.trace.BlankSpan
io.opencensus.trace.AutoValue_EndSpanOptions was unintentionally initialized at build time. To see why io.opencensus.trace.AutoValue_EndSpanOptions got initialized use --trace-class-initialization=io.opencensus.trace.AutoValue_EndSpanOptions
io.opencensus.trace.Span was unintentionally initialized at build time. To see why io.opencensus.trace.Span got initialized use --trace-class-initialization=io.opencensus.trace.Span
com.google.common.collect.ImmutableList was unintentionally initialized at build time. To see why com.google.common.collect.ImmutableList got initialized use --trace-class-initialization=com.google.common.collect.ImmutableList
com.google.api.client.http.javanet.NetHttpTransport was unintentionally initialized at build time. To see why com.google.api.client.http.javanet.NetHttpTransport got initialized use --trace-class-initialization=com.google.api.client.http.javanet.NetHttpTransport
com.google.common.collect.RegularImmutableList was unintentionally initialized at build time. To see why com.google.common.collect.RegularImmutableList got initialized use --trace-class-initialization=com.google.common.collect.RegularImmutableList
com.google.cloud.PlatformInformation was unintentionally initialized at build time. To see why com.google.cloud.PlatformInformation got initialized use --trace-class-initialization=com.google.cloud.PlatformInformation
com.google.api.client.http.OpenCensusUtils was unintentionally initialized at build time. To see why com.google.api.client.http.OpenCensusUtils got initialized use --trace-class-initialization=com.google.api.client.http.OpenCensusUtils
com.google.common.base.Throwables was unintentionally initialized at build time. To see why com.google.common.base.Throwables got initialized use --trace-class-initialization=com.google.common.base.Throwables
com.google.api.client.http.HttpMediaType was unintentionally initialized at build time. To see why com.google.api.client.http.HttpMediaType got initialized use --trace-class-initialization=com.google.api.client.http.HttpMediaType
com.google.api.client.http.HttpTransport was unintentionally initialized at build time. To see why com.google.api.client.http.HttpTransport got initialized use --trace-class-initialization=com.google.api.client.http.HttpTransport
io.opencensus.trace.EndSpanOptions was unintentionally initialized at build time. To see why io.opencensus.trace.EndSpanOptions got initialized use --trace-class-initialization=io.opencensus.trace.EndSpanOptions
com.google.common.io.Closer was unintentionally initialized at build time. To see why com.google.common.io.Closer got initialized use --trace-class-initialization=com.google.common.io.Closer
com.google.api.client.http.HttpRequest was unintentionally initialized at build time. To see why com.google.api.client.http.HttpRequest got initialized use --trace-class-initialization=com.google.api.client.http.HttpRequest
com.google.cloud.ServiceOptions was unintentionally initialized at build time. To see why com.google.cloud.ServiceOptions got initialized use --trace-class-initialization=com.google.cloud.ServiceOptions
com.google.api.client.util.escape.CharEscapers was unintentionally initialized at build time. To see why com.google.api.client.util.escape.CharEscapers got initialized use --trace-class-initialization=com.google.api.client.util.escape.CharEscapers
com.google.api.client.util.Data was unintentionally initialized at build time. To see why com.google.api.client.util.Data got initialized use --trace-class-initialization=com.google.api.client.util.Data
io.opencensus.trace.Status was unintentionally initialized at build time. To see why io.opencensus.trace.Status got initialized use --trace-class-initialization=io.opencensus.trace.Status
com.google.api.client.util.DateTime was unintentionally initialized at build time. To see why com.google.api.client.util.DateTime got initialized use --trace-class-initialization=com.google.api.client.util.DateTime

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1

```

**Comment by viniciusccarvalho** [comment]
This is a version issue for sure, as I mentioned on the google repo, current version of micronaut-gcp 3.4.0 is pulling libs that are not compatible with google graalvm. As I said I was able to do this a while back, but I also used the latest snapshot 3.4.1 built locally.

You can:

pull latest repo and do a .gradlew publishToMavenLocal and in your project add mavenLocal() and update deps to 3.4.1-SNAPSHOT

Or wait for the new version to drop. 

I've updated your project to 3.4.1 and it compiled:

`Native Image written to: /Users/vinicius/projects/java/issues/micronaut-gcp-logs/build/native-image/application`

@graemerocher we should probably find a way to follow the bom that is referred on https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support I don't think we are at the moment. That would make graal integration easier I think.
