### ISSUE TITLE
Failed to build graalvm native image for package micronaut-gcp-logging

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-gcp#439]
I couldn't build native image as soon as I used `implementation("io.micronaut.gcp:micronaut-gcp-logging:3.5.0")` package.
Resulting this error : 
```
Detailed message:
Error: No instances of java.net.PlainSocketImpl are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the io.micronaut.runtime.Micronaut class initializer with a trace: 
        at java.net.PlainSocketImpl.<init>(PlainSocketImpl.java:49)
        at java.net.Socket.<init>(Socket.java:148)
        at sun.net.NetworkClient.createSocket(NetworkClient.java:199)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at sun.net.www.http.HttpClient.New(HttpClient.java:362)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.isGoogleCompute(GoogleCloudPropertyDefiner.java:66)
        at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.getPropertyValue(GoogleCloudPropertyDefiner.java:55)
        at ch.qos.logback.core.joran.action.DefinePropertyAction.end(DefinePropertyAction.java:100)
        at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
        at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
        at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
        at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:49)
```

If a remove this package, the build is successful. 
Here is a sample project : https://github.com/tchiotludo/micronaut-gcp-logs

**Comment by sgammon** [comment]
+1

```
Error: No instances of java.net.PlainSocketImpl are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the io.micronaut.runtime.Micronaut class initializer with a trace: 
 	at java.net.PlainSocketImpl.<init>(PlainSocketImpl.java:49)
	at java.net.Socket.<init>(Socket.java:148)
	at sun.net.NetworkClient.createSocket(NetworkClient.java:199)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.isGoogleCompute(GoogleCloudPropertyDefiner.java:66)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.getPropertyValue(GoogleCloudPropertyDefiner.java:55)
	at ch.qos.logback.core.joran.action.DefinePropertyAction.end(DefinePropertyAction.java:100)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:49)

```

**Comment by sdelamo** [comment]
your sample app 404 for me. I assume this is fixed in Micronaut Framework 4 https://github.com/micronaut-projects/micronaut-gcp/issues/792
