### ISSUE TITLE
Error building native imagen

### ISSUE THREAD

**Issue by j1cs** [micronaut-projects/micronaut-gcp#523]
### Expected Behavior

trying to build a native image in a continuous integration pipeline (gitlab in this case)

### Actual Behaviour

trying to build a native image in a continuous integration pipeline generates error.
````
Error: No instances of jdk.internal.misc.InnocuousThread are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the io.micronaut.runtime.Micronaut class initializer with a trace: 
 	at jdk.internal.misc.InnocuousThread.<init>(InnocuousThread.java:100)
	at jdk.internal.misc.InnocuousThread$2.run(InnocuousThread.java:93)
	at jdk.internal.misc.InnocuousThread$2.run(InnocuousThread.java:90)
	at java.security.AccessController.doPrivileged(Unknown Source)
	at jdk.internal.misc.InnocuousThread.newSystemThread(InnocuousThread.java:89)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:106)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:104)
	at java.security.AccessController.doPrivileged(Unknown Source)
	at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:104)
	at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:449)
	at sun.net.www.http.HttpClient.finished(HttpClient.java:406)
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:99)
	at sun.net.www.MeteredStream.justRead(MeteredStream.java:93)
	at sun.net.www.MeteredStream.read(MeteredStream.java:135)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.isGoogleCompute(GoogleCloudPropertyDefiner.java:70)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.getPropertyValue(GoogleCloudPropertyDefiner.java:55)
	at ch.qos.logback.core.joran.action.DefinePropertyAction.end(DefinePropertyAction.java:100)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:50)
.  To fix the issue mark jdk.internal.misc.InnocuousThread for build-time initialization with --initialize-at-build-time=jdk.internal.misc.InnocuousThread or use the the information from the trace to find the culprit and --initialize-at-run-time=<culprit> to prevent its instantiation.
Detailed message:
Trace: Object was reached by 
	reading field sun.net.www.http.KeepAliveCache.keepAliveTimer of
		constant sun.net.www.http.KeepAliveCache@65a19ff8 reached by 
	reading field sun.net.www.http.HttpClient.kac
com.oracle.svm.core.util.UserError$UserException: No instances of jdk.internal.misc.InnocuousThread are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the io.micronaut.runtime.Micronaut class initializer with a trace: 
 	at jdk.internal.misc.InnocuousThread.<init>(InnocuousThread.java:100)
	at jdk.internal.misc.InnocuousThread$2.run(InnocuousThread.java:93)
	at jdk.internal.misc.InnocuousThread$2.run(InnocuousThread.java:90)
	at java.security.AccessController.doPrivileged(Unknown Source)
	at jdk.internal.misc.InnocuousThread.newSystemThread(InnocuousThread.java:89)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:106)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:104)
	at java.security.AccessController.doPrivileged(Unknown Source)
	at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:104)
	at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:449)
	at sun.net.www.http.HttpClient.finished(HttpClient.java:406)
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:99)
	at sun.net.www.MeteredStream.justRead(MeteredStream.java:93)
	at sun.net.www.MeteredStream.read(MeteredStream.java:135)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.isGoogleCompute(GoogleCloudPropertyDefiner.java:70)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.getPropertyValue(GoogleCloudPropertyDefiner.java:55)
	at ch.qos.logback.core.joran.action.DefinePropertyAction.end(DefinePropertyAction.java:100)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:50)
.  To fix the issue mark jdk.internal.misc.InnocuousThread for build-time initialization with --initialize-at-build-time=jdk.internal.misc.InnocuousThread or use the the information from the trace to find the culprit and --initialize-at-run-time=<culprit> to prevent its instantiation.
Detailed message:
Trace: Object was reached by 
	reading field sun.net.www.http.KeepAliveCache.keepAliveTimer of
		constant sun.net.www.http.KeepAliveCache@65a19ff8 reached by 
	reading field sun.net.www.http.HttpClient.kac
	at com.oracle.svm.core.util.UserError.abort(UserError.java:82)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:233)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:764)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:532)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of jdk.internal.misc.InnocuousThread are allowed in the image heap as this class should be initialized at image runtime. Object has been initialized by the io.micronaut.runtime.Micronaut class initializer with a trace: 
 	at jdk.internal.misc.InnocuousThread.<init>(InnocuousThread.java:100)
	at jdk.internal.misc.InnocuousThread$2.run(InnocuousThread.java:93)
	at jdk.internal.misc.InnocuousThread$2.run(InnocuousThread.java:90)
	at java.security.AccessController.doPrivileged(Unknown Source)
	at jdk.internal.misc.InnocuousThread.newSystemThread(InnocuousThread.java:89)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:106)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:104)
	at java.security.AccessController.doPrivileged(Unknown Source)
	at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:104)
	at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:449)
	at sun.net.www.http.HttpClient.finished(HttpClient.java:406)
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:99)
	at sun.net.www.MeteredStream.justRead(MeteredStream.java:93)
	at sun.net.www.MeteredStream.read(MeteredStream.java:135)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3510)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.isGoogleCompute(GoogleCloudPropertyDefiner.java:70)
	at io.micronaut.gcp.logging.GoogleCloudPropertyDefiner.getPropertyValue(GoogleCloudPropertyDefiner.java:55)
	at ch.qos.logback.core.joran.action.DefinePropertyAction.end(DefinePropertyAction.java:100)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:50)
.  To fix the issue mark jdk.internal.misc.InnocuousThread for build-time initialization with --initialize-at-build-time=jdk.internal.misc.InnocuousThread or use the the information from the trace to find the culprit and --initialize-at-run-time=<culprit> to prevent its instantiation.
Detailed message:
Trace: Object was reached by 
	reading field sun.net.www.http.KeepAliveCache.keepAliveTimer of
		constant sun.net.www.http.KeepAliveCache@65a19ff8 reached by 
	reading field sun.net.www.http.HttpClient.kac
	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:761)
	... 6 more
````

### Steps To Reproduce

1. in gitlab ci pipelines
2. with a project with the follows features: graalvm,reactor,lombok,gcp-pubsub,testcontainers
3. adding extra dependecy called com.google.cloud native-image-support
4. configure loggin https://micronaut-projects.github.io/micronaut-gcp/latest/guide/#_dynamic_appender_selection

### Environment Information

- Gitlab CI Pipelines
- Docker image "ghcr.io/graalvm/graalvm-ce:java11-21.3.0" as builder

### Version

3.1.4

**Comment by viniciusccarvalho** [comment]
Have you tried enabling http-protocols on the native build: https://www.graalvm.org/reference-manual/native-image/URLProtocols/.

@graemerocher do we enable them by default on the native image generation? I've seen folks on StackOverflow complaining about the HttpUrlHandler of the jvm not working with graalvm. This is where this error is coming from

**Comment by viniciusccarvalho** [comment]
On my mac os image is building, and app starts normally (I have not configured google cloud credentials) but I see that the logger is getting configured. I'll try to setup a gitlab pipeline (never used gitlab before) and see if I find anything there

**Comment by viniciusccarvalho** [comment]
I'm unable to reproduce this error. I've setup a project at https://github.com/viniciusccarvalho/gcp-native-error and using the following github action (very similar to what a gitlab pipeline would be)

```

name: Build and release
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.3.0.java11'

      - name: Install GraalVM's native-image extension
        run: gu install native-image
        
      - name: gradle build
        run: ./gradlew nativeImage
```

The image is built with no errors

**Comment by j1cs** [comment]
I understand what you are saying. i will try to enable http-protocols as you say.
I want to add that I am using the [google cloud library](https://github.com/GoogleCloudPlatform/native-image-support-java) and it is inside has the [native-image.properties](https://github.com/GoogleCloudPlatform/native-image-support-java/blob/master/native-image-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-graalvm-support/native-image.properties) file with the following content:
```
Args = --allow-incomplete-classpath \
--enable-url-protocols=https,http \
--initialize-at-build-time=org.conscrypt \
--initialize-at-run-time=io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl,\
    io.grpc.netty.shaded.io.netty.internal.tcnative.SSL,\
    io.grpc.netty.shaded.io.netty.internal.tcnative.CertificateVerifier,\
    io.grpc.netty.shaded.io.netty.internal.tcnative.SSLPrivateKeyMethod,\
    io.grpc.netty.shaded.io.grpc.netty,\
    io.grpc.netty.shaded.io.netty.channel.epoll,\
    io.grpc.netty.shaded.io.netty.channel.unix,\
    io.grpc.netty.shaded.io.netty.handler.ssl,\
    io.grpc.internal.RetriableStream,\
    com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion,\
    com.google.cloud.firestore.FirestoreImpl
```
I don't know if this configuration also applies to this problem.

**Comment by viniciusccarvalho** [comment]
The sample project is using the exact same imports as you reported, including the gcp support for native image. The only thing that is different here is the build image. But I got this to work on my mac as well on a ubuntu docker on my docker environment.

**Comment by ilopmar** [comment]
Regarding the protocols, yes, we do enable them https://github.com/micronaut-projects/micronaut-core/blob/3.1.x/inject/src/main/resources/META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties#L18

**Comment by j1cs** [comment]
> The sample project is using the exact same imports as you reported, including the gcp support for native image. The only thing that is different here is the build image. But I got this to work on my mac as well on a ubuntu docker on my docker environment.

We're currently using gitlab ci with our own runners, these runners are configured to use docker as a service and they work with other projects. However, when running the pipeline for a micronaut project we're getting this exact same error even though we're using a multistage dockerfile with the GraalVM image as base for builds. Here's the dockerfile:

```
FROM ghcr.io/graalvm/graalvm-ce:java11-21.3.0 AS builder
RUN gu install native-image
WORKDIR /home/app
COPY . /home/app
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
RUN ./mvnw -T 1C package -Dpackaging=native-image -Pgraalvm


FROM frolvlad/alpine-glibc:alpine-3.12
RUN apk update && apk add libstdc++
COPY --from=builder /home/app/target/product-to-outbound-event /app/application

EXPOSE 8080
ENTRYPOINT ["/app/application"]
```

> The sample project is using the exact same imports as you reported, including the gcp support for native image. The only thing that is different here is the build image. But I got this to work on my mac as well on a ubuntu docker on my docker environment.

I see. Thanks for your response.

**Comment by j1cs** [comment]
Looks like it seems related to https://github.com/micronaut-projects/micronaut-core/issues/3683

**Comment by j1cs** [comment]
I think this [issue](https://github.com/micronaut-projects/micronaut-core/issues/3683) is related because [Micronaut.java](https://github.com/micronaut-projects/micronaut-core/blob/3.1.x/context/src/main/java/io/micronaut/runtime/Micronaut.java#L50) calls `org.slf4j.LoggerFactory.getLogger` which triggers the error.
I don't know if I can override [GoogleCloudPropertyDefiner](https://github.com/micronaut-projects/micronaut-gcp/blob/c9f63645a2dde5efe80660760af12f23aff6ff24/gcp-logging/src/main/java/io/micronaut/gcp/logging/GoogleCloudPropertyDefiner.java#L37) to avoid going through that block of code at build time

**Comment by j1cs** [comment]
also according to the log above it should fall in the exception and return false. but what it shows is that it's trying to get metadata from http://metadata.google.internal as seen here in the line 71: https://github.com/micronaut-projects/micronaut-gcp/blob/c9f63645a2dde5efe80660760af12f23aff6ff24/gcp-logging/src/main/java/io/micronaut/gcp/logging/GoogleCloudPropertyDefiner.java#L65-L73
is it because the runners run on google cloud platform? 
as it says here https://docs.gitlab.com/ee/ci/runners/runner_cloud/linux_runner_cloud.html
and as you can see in the configuration in gitlab https://i.imgur.com/XU6sfOK.png

**Comment by viniciusccarvalho** [comment]
Got it to be reproduced now, indeed only happens at GCP. Locally, github, bitbucket tried all of them and they all work. Using google cloud build to build the Dockernativefile created by micronaut, and the one I used for all other experiments the error indeed happens.

@ilopmar and @graemerocher you guys have way more experience with graalvm, this seems a bit odd to me, why would the graalvm compiler have issues with it. 

I'll reach out to my friends at Google Cloud to check if they've seen this error with the native library integration, not sure if they have tried building this on gcp or just locally.

In the meantime it may be possible to add a custom `native-image.properties` to forcibly initialize that class and bypass this.

**Comment by viniciusccarvalho** [comment]
@j1cs There's a solution for this problem which is not using the DynamicAppender at all. I've only added it because it was annoying having to switch back and forth, from local runs and cloud deployments.

But you can easily just use 
```<configuration>
    <appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="io.micronaut.gcp.logging.StackdriverJsonLayout">
                <projectId>${projectId}</projectId> 
                <includeTraceId>true</includeTraceId>
                <includeSpanId>true</includeSpanId>
                <includeLevel>true</includeLevel>
                <includeThreadName>false</includeThreadName>
                <includeMDC>true</includeMDC>
                <includeLoggerName>true</includeLoggerName>
                <includeFormattedMessage>true</includeFormattedMessage>
                <includeExceptionInMessage>true</includeExceptionInMessage>
                <includeContextName>true</includeContextName>
                <includeMessage>false</includeMessage>
                <includeException>false</includeException>
            </layout>
        </encoder>
    </appender>
    <root level="INFO">
        <appender-ref ref="CONSOLE_JSON" >

        </appender-ref>
    </root>
</configuration>```
in your logback.xml and this problem will go away.

You can do some CI manipulation of files, and have a logback-cloud and override the logback.xml if you are deploying on the cloud. This would make your local executions and cloud deployments work just fine.

I would just do this for the moment, the workaround is not that trivial, since GraalVM 19 a bunch of remote classes have been removed from being able to be used in build-time see https://stackoverflow.com/questions/63328298/how-do-you-debug-a-no-instances-of-are-allowed-in-the-image-heap-when-buil. 

I've started working on a substitution, but even the graalvm folks recommend against it, the solution is not going to be trivial I think.

In the mean time just move away from the dynamic appender.

**Comment by j1cs** [comment]
I understand what you are saying but when the build is done and the artifact is created for deployment (which is a native image) inside it will already have the logback file that was added in the build and will be used in the deployment later. 
then there would have to be some argument in the native image to tell it what file to take. from what I looked for apparently it can't be done.
could you exemplify the workaround you point out? maybe I'm wrong and I don't see the whole picture.

**Comment by viniciusccarvalho** [comment]
Only if your build has the logback that uses the Google dynamic appender. I have built an image inside gcp using the logback example above. It works as expected.

As per how you would do this, depends on your ci tool. You can have a step that renames the logback.gcp (which would never be picked up by logback, nor included in the native image because its not part of the resources inclusion in the json), rename it to logback.xml and override the logback.xml that has the default micronaut one for instance.

So during your build, the final asset is modified before packaging, that's what I'm talking. 

How you would do this, it really depends on your tooling, gitlab pipelines probably have support for something like this.

**Comment by j1cs** [comment]
@viniciusccarvalho I'm not sure if you can do that because the build and packaging process happens at the same time running :
`$ ./mvnw package -Dpackaging=native-image -Pgraalvm`
so I don't see at what point the substitution can be made.

**Comment by viniciusccarvalho** [comment]
before you call gradle, the pipeline is composed of steps, before the step to compile change the file name or create a gradle task to do so and make the compile task depend on that.

**Comment by j1cs** [comment]
> before you call gradle, the pipeline is composed of steps, before the step to compile change the file name or create a gradle task to do so and make the compile task depend on that.

ah ok. but i'm not using gradle sadly :(. Can i do the same with maven? :)

**Comment by viniciusccarvalho** [comment]
yep

**Comment by sdelamo** [comment]
@j1cs can we close this issue or is this issue still present with Micronaut Framework 4?

**Comment by j1cs** [comment]
> @j1cs can we close this issue or is this issue still present with Micronaut Framework 4?

i don't know really. if it happens to me again I will report it.
